name: build-ios

on:
  workflow_dispatch:

env:
  LIB_NAME: libindy
  HEADER_FILE: libindy/include
  PACKAGE: indy-vdr

jobs:
  workflow-setup:
    name: workflow setup
    runs-on: ubuntu-latest
    outputs:
      LIBINDY_CACHE_KEY: ${{ steps.mainstep.outputs.LIBINDY_CACHE_KEY }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set outputs
        id: mainstep
        run: |
          LIBINDY_CACHE_KEY="v1-$(git rev-parse HEAD:libindy)"
          echo "LIBINDY_CACHE_KEY=$LIBINDY_CACHE_KEY"
          echo "::set-output name=LIBINDY_CACHE_KEY::$LIBINDY_CACHE_KEY"
  build_ios:
    name: build
    runs-on: macos-latest
    needs: workflow-setup
    strategy:
      matrix:
        architecture: [aarch64-apple-ios, aarch64-apple-ios-sim, x86_64-apple-ios]
#        architecture: [aarch64-apple-ios, aarch64-apple-ios-sim, x86_64-apple-ios]
    steps:
      - name: Cache build
        uses: actions/cache@v3
        id: cargo-cache
        with:
          path: |
            libindy/target/${{matrix.architecture}}/release/${{ env.LIB_NAME }}.a
          key: ${{ runner.os }}-cargo-${{matrix.architecture}}-${{needs.workflow-setup.outputs.LIBINDY_CACHE_KEY}}
      - uses: actions/checkout@v2
        if: steps.cargo-cache.outputs.cache-hit != 'true'
      - name: brew install zeromq
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: brew install zeromq
      - name: brew info openssl
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: brew --prefix openssl@1.1
      - name: Build
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        env:
            PKG_CONFIG_ALLOW_CROSS: 1
            OPENSSL_DIR: /usr/local/opt/openssl@1.1
        run: |
          rustup default "1.60.0"
          rustup target add ${{matrix.architecture}}
          cargo build --verbose --manifest-path libindy/Cargo.toml --target ${{matrix.architecture}} --release
      - name: Save static library
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.architecture}}
          path: libindy/target/${{ matrix.architecture }}/release/${{ env.LIB_NAME }}.a

  create_libindy_xcframework:
    name: Build libindy xcframework
    runs-on: macos-latest
    needs: build_ios
    steps:
      - uses: actions/checkout@v2
      - name: Fetch static libraries
        uses: actions/download-artifact@v3
      - run: >
          lipo -create aarch64-apple-ios-sim/${{ env.LIB_NAME }}.a \
                       x86_64-apple-ios/${{ env.LIB_NAME }}.a \
               -output ${{ env.LIB_NAME }}.a
      - run: >
          xcodebuild -create-xcframework \
            -library aarch64-apple-ios/${{ env.LIB_NAME }}.a -headers ${{ env.HEADER_FILE }} \
            -library ${{ env.LIB_NAME }}.a                   -headers ${{ env.HEADER_FILE }} \
            -output Frameworks/${{ env.LIB_NAME }}.xcframework
          zip -r "${{ env.LIB_NAME }}.zip" Frameworks/*
      - name: Save xcframework
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.LIB_NAME }}
          path: ${{ env.LIB_NAME }}.zip
#      - name: Save xcframework
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ LIB_NAME }}.xcframework
#          path: Frameworks/${{ LIB_NAME }}.xcframework
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            aarch64-apple-ios
            aarch64-apple-ios-sim
            x86_64-apple-ios
          failOnError: false

  create_libindy_objc_xcframework:
    name: Build indy-objc xcframework
    runs-on: macos-latest
    needs: create_libindy_xcframework
    steps:
      - name: Cache Package
        uses: actions/cache@v3
        id: libindy-objc-cache
        with:
          path: wrappers/ios/libindy-pod/xcarchive/libindy-objc.zip
          key: ${{ runner.os }}-libindy-objc-${{needs.workflow-setup.outputs.LIBINDY_CACHE_KEY}}
      - uses: actions/checkout@v2
        if: steps.libindy-objc-cache.outputs.cache-hit != 'true'
      - name: Fetch static libraries
        if: steps.libindy-objc-cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.LIB_NAME }}
          path: libindy/target/libindy
      - name: Display structure of downloaded files
        if: steps.libindy-objc-cache.outputs.cache-hit != 'true'
        run: set -x; pwd; ls -laR; mv libindy/libindy.zip ./ ; ls -laR
        working-directory: libindy/target
      - name: pod install
        if: steps.libindy-objc-cache.outputs.cache-hit != 'true'
        run: pod install --verbose
        working-directory: wrappers/ios/libindy-pod
      - name: Build for iphoneos
        if: steps.libindy-objc-cache.outputs.cache-hit != 'true'
        run: xcodebuild -workspace Indy.xcworkspace -scheme Indy -configuration Release -sdk iphoneos -archivePath Indy-Device.xcarchive -verbose clean archive EXCLUDED_ARCHS=armv7
        working-directory: wrappers/ios/libindy-pod
      - name: Build for iphonesimulator
        if: steps.libindy-objc-cache.outputs.cache-hit != 'true'
        run: xcodebuild -workspace Indy.xcworkspace -scheme Indy -configuration Release -sdk iphonesimulator -archivePath Indy-Simulator.xcarchive -verbose clean archive "EXCLUDED_ARCHS=arm64 i386"
        working-directory: wrappers/ios/libindy-pod
      - name: package
        if: steps.libindy-objc-cache.outputs.cache-hit != 'true'
        working-directory: wrappers/ios/libindy-pod
        run: >
          mkdir -p xcarchive/Frameworks
          xcodebuild -create-xcframework \
            -framework Indy-Device.xcarchive/Products/Library/Frameworks/Indy.framework \
            -framework Indy-Simulator.xcarchive/Products/Library/Frameworks/Indy.framework \
            -output xcarchive/Frameworks/Indy.xcframework
          cd xcarchive
          zip -r "libindy-objc.zip" Frameworks/*
      - name: publish artifact
        run: |
          set -x
          find . -type f -name libindy-objc.zip
          curl -H "X-JFrog-Art-Api:${{ secrets.ARTIFACTORY_API_KEY }}" -T wrappers/ios/libindy-pod/xcarchive/libindy-objc.zip "https://cvarjao.jfrog.io/artifactory/default-generic-local/latest/libindy-objc.zip"
