name: build-ios

on:
  workflow_dispatch:

env:
  LIB_NAME: libindy
  HEADER_FILE: libindy/include
  PACKAGE: indy-vdr

jobs:
  workflow-setup:
    name: workflow setup
    runs-on: ubuntu-latest
    outputs:
      LIBINDY_CACHE_KEY: ${{ steps.mainstep.outputs.LIBINDY_CACHE_KEY }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set outputs
        id: mainstep
        run: |
          LIBINDY_CACHE_KEY="v1-$(git rev-parse HEAD:libindy)"
          echo "LIBINDY_CACHE_KEY=$LIBINDY_CACHE_KEY"
          echo "::set-output name=LIBINDY_CACHE_KEY::$LIBINDY_CACHE_KEY"
  build_ios:
    name: build
    runs-on: macos-latest
    needs: workflow-setup
    strategy:
      matrix:
        architecture: [aarch64-apple-ios, aarch64-apple-ios-sim, x86_64-apple-ios]
#        architecture: [aarch64-apple-ios, aarch64-apple-ios-sim, x86_64-apple-ios]
    steps:
      - name: Cache build
        uses: actions/cache@v3
        id: cargo-cache
        with:
          path: |
            libindy/target/${{matrix.architecture}}/release/${{ env.LIB_NAME }}.a
          key: ${{ runner.os }}-cargo-${{matrix.architecture}}-${{needs.workflow-setup.outputs.LIBINDY_CACHE_KEY}}
      - uses: actions/checkout@v2
        if: steps.cargo-cache.outputs.cache-hit != 'true'
      - name: brew install zeromq
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: brew install zeromq
      - name: brew info openssl
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: brew --prefix openssl@1.1
      - name: Build
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        env:
            PKG_CONFIG_ALLOW_CROSS: 1
            OPENSSL_DIR: /usr/local/opt/openssl@1.1
        run: |
          rustup default "1.60.0"
          rustup target add ${{matrix.architecture}}
          cargo build --verbose --manifest-path libindy/Cargo.toml --target ${{matrix.architecture}} --release
      - name: Save static library
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.architecture}}
          path: libindy/target/${{ matrix.architecture }}/release/${{ env.LIB_NAME }}.a

  create_libindy_xcframework:
    name: Build libindy xcframework
    runs-on: macos-latest
    needs: build_ios
    steps:
      - uses: actions/checkout@v2
      - name: Fetch static libraries
        uses: actions/download-artifact@v3
      - run: >
          lipo -create aarch64-apple-ios-sim/${{ env.LIB_NAME }}.a \
                       x86_64-apple-ios/${{ env.LIB_NAME }}.a \
               -output ${{ env.LIB_NAME }}.a
      - run: >
          xcodebuild -create-xcframework \
            -library aarch64-apple-ios/${{ env.LIB_NAME }}.a -headers ${{ env.HEADER_FILE }} \
            -library ${{ env.LIB_NAME }}.a                   -headers ${{ env.HEADER_FILE }} \
            -output Frameworks/${{ env.LIB_NAME }}.xcframework
          zip -r "${{ env.LIB_NAME }}.zip" Frameworks/*
      - name: Save xcframework
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.LIB_NAME }}.zip
          path: ${{ env.LIB_NAME }}.zip
#      - name: Save xcframework
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ LIB_NAME }}.xcframework
#          path: Frameworks/${{ LIB_NAME }}.xcframework
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            aarch64-apple-ios
            aarch64-apple-ios-sim
            x86_64-apple-ios
          failOnError: false

  create_libindy_objc_xcframework:
    name: Build indy-objc xcframework
    runs-on: macos-latest
    needs: create_libindy_xcframework
    steps:
      - uses: actions/checkout@v2
      - name: Fetch static libraries
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.LIB_NAME }}.zip
          path: libindy/target/libindy.zip
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: libindy/target