name: build-ios

on:
  workflow_dispatch:

env:
  LIB_NAME: libindy
  HEADER_FILE: libindy/include
  PACKAGE: indy-vdr

jobs:
  build_ios:
    name: build
    runs-on: macos-latest
    strategy:
      matrix:
        architecture: [aarch64-apple-ios, aarch64-apple-ios-sim, x86_64-apple-ios]
#        architecture: [aarch64-apple-ios, aarch64-apple-ios-sim, x86_64-apple-ios]
    steps:
      - name: Cache build
        uses: actions/cache@v3
        id: cargo-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{matrix.architecture}}-${{ hashFiles('libindy/Cargo.lock') }}
      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: "1.60.0"
#          target: ${{matrix.architecture}}
      - name: brew install zeromq
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: brew install zeromq
      - name: brew info openssl
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: brew --prefix openssl@1.1
      - name: Build
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        env:
            PKG_CONFIG_ALLOW_CROSS: 1
            OPENSSL_DIR: /usr/local/opt/openssl@1.1
        run: |
          rustup default "1.60.0"
          rustup target add ${{matrix.architecture}}
          cargo build --verbose --manifest-path libindy/Cargo.toml --target ${{matrix.architecture}} --release
#      - uses: actions-rs/cargo@v1
#        with:
#          use-cross: true
#          command: build
#          args: --manifest-path libindy/Cargo.toml --target ${{matrix.architecture}} --release --all-features
      - name: Save static library
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.architecture}}
          path: libindy/target/${{ matrix.architecture }}/release/${{ env.LIB_NAME }}.a

  create_ios_xcframework:
    name: Create ios xcframework
    runs-on: macos-latest
    needs: build_ios
    steps:
      - uses: actions/checkout@v2
      - name: Fetch static libraries
        uses: actions/download-artifact@v3
      - run: >
          lipo -create aarch64-apple-ios-sim/${{ env.LIB_NAME }}.a \
                       x86_64-apple-ios/${{ env.LIB_NAME }}.a \
               -output ${{ env.LIB_NAME }}.a
      - run: >
          xcodebuild -create-xcframework \
            -library aarch64-apple-ios/${{ env.LIB_NAME }}.a -headers ${{ env.HEADER_FILE }} \
            -library ${{ env.LIB_NAME }}.a                   -headers ${{ env.HEADER_FILE }} \
            -output ${{ env.LIB_NAME }}.xcframework
#      - name: Save xcframework
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ LIB_NAME }}.xcframework
#          path: ${{ LIB_NAME }}.xcframework
#      - uses: geekyeggo/delete-artifact@v1
#        with:
#          name: |
#            aarch64-apple-ios
#            aarch64-apple-ios-sim
#            x86_64-apple-ios
#          failOnError: false
