name: indy-sdk-ios

on:
  workflow_dispatch:

env:
  RUST_VER: 1.58.0
  POOL_IP: "127.0.0.1"
  DEVICE_ABIS: "arm arm64"
  EMULATOR_ABIS: "x86 x86_64"

jobs:
  workflow-setup:
    runs-on: ubuntu-latest
    outputs:
      PUBLISH_VERSION: ${{ steps.mainstep.outputs.PUBLISH_VERSION }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VER }}
      - name: Set outputs
        id: mainstep
        run: |
          PUBLISH_VERSION="1.15.0"
          echo "::set-output name=PUBLISH_VERSION::$PUBLISH_VERSION"
          echo "::set-output name=LIBINDY_CACHE_KEY::$(git rev-parse HEAD:libindy)"
  build-ios:
    runs-on: macos-11
    needs:
      - workflow-setup
    env:
      PUBLISH_VERSION: ${{ needs.workflow-setup.outputs.PUBLISH_VERSION }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Cache libindy
      id: cache-libindy
      uses: actions/cache@v3
      with:
        path: libindy/out_pod/libindy.tar.gz
        key: ${{ runner.os }}-libindy-${{steps.workflow-setup.outputs.LIBINDY_CACHE_KEY}}
    - name: Build iOS wrapper
      if: steps.cache-libindy.outputs.cache-hit != 'true'
      run: |
          LIBINDY_POD_VERSION=${{ env.PUBLISH_VERSION }} RUST_VER=${{ env.RUST_VER }} ./ci/ga-ios-build.sh libindy "aarch64-apple-ios,x86_64-apple-ios"
    - name: Install Dependencies
      run: |
        cd ./wrappers/ios/libindy-pod
        pod install --repo-update
    - name: Install Dependencies
      run: |
        cd ./wrappers/ios/libindy-pod
        cat << EOF > config-file
        MARKETING_VERSION = ${{ steps.mainstep.outputs.PUBLISH_VERSION }}
        CURRENT_PROJECT_VERSION = 99
        CODE_SIGNING_REQUIRES_TEAM = YES
        DEVELOPMENT_TEAM = SQ65UM6V94
        EOF
        cat config-file
    - name: Install Dependencies
      run: |
        cd ./wrappers/ios/libindy-pod
        xcodebuild -workspace Indy.xcworkspace -scheme Indy clean archive -configuration release -sdk iphoneos -archivePath Indy-Device.xcarchive -xcconfig config-file
#    - uses: actions/upload-artifact@v2
#      with:
#        name: libindy-ios-${{ env.PUBLISH_VERSION }}-universal
#        path: ./libindy/out_pod/libindy.tar.gz
